# This action requests a region of a geographic map.

string url            # where to read map data

# Bounding box for the desired map.  If global, provide all data
# available from the specified URL.
BoundingBox bounds

---

# Result:

bool success          # true if the call succeeded
string status         # more details

# The requested map, its bounds may differ from the requested bounds.
GeographicMap map

---

# Feedback:

float32 progress      # progress meter: 0.0 (start) to 1.0 (done)
